import numpy as np
from cluster.kmeans import KMeans
from cluster.silhouette import Silhouette
import sklearn

from cluster.utils import make_clusters


def test_silhouette():
    """
    compare scoring funciton to sklearn for a small input
    """
    X = np.array([[0.0, 0.0],
                  [1.0, 1.0],
                  [10.0, 10.0],
                  [11.0, 11.0]])

    km = KMeans(k=2)
    km.fit(X)
    labels = km.predict(X)

    sil = Silhouette()
    scores = sil.score(X, labels)
    mean_my_score = np.mean(scores) # take mean since sklearn reports the averge score
    # compare the score i get from my Silhouette class to sklearn.metrics.silhouette_score
    sklearn_score = sklearn.metrics.silhouette_score(X, labels)

    assert np.allclose(mean_my_score, sklearn_score, atol=1e-2)

def test_silhouette_generated_data():
    """
    compare scoring funciton to sklearn for a larger input generated by the provided code
    """
    points, true_labels = make_clusters(n=100, k=5)
    km = KMeans(k=5)
    km.fit(points)
    pred_labels = km.predict(points)
    sil = Silhouette()
    scores = sil.score(points, pred_labels)
    mean_my_score = np.mean(scores) # take the mean since sklear reports the averge score
    sklearn_score = sklearn.metrics.silhouette_score(points, pred_labels)
    # compare the score i get from my Silhouette class to sklearn.metrics.silhouette_score
    assert np.allclose(mean_my_score, sklearn_score, atol=1e-2)